services:
  noip:
    image: qmcgaw/ddns-updater:latest
    container_name: noip-ddns
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /srv/data/noip:/updater/data
    env_file:
      - ../../env/common.env
      - ../../env/secrets.env
    environment:
      - PERIOD=5m
      - LOG_LEVEL=info
      - PUBLICIP_HTTP_PROVIDERS=all